import { ContentBlock } from "./mockDataBackend";

export interface Article {
  id: string;
  title: string;
  summary: string;
  keyPoints: string[];
  fullContent: string;
  location: string;
  category: string;
  imageUrl: string;
  publishedAt: string;
  updatedAt: string;
  isNew?: boolean;
  isTrending?: boolean;
  aiSummaryBlocks?: ContentBlock[];
}

export interface WeeklyRecapCategory {
  id: string;
  name: string;
  icon: string;
  articles: Article[];
}

export const availableLocations = [
  "Aalst",
  "Aarle-Rixtel",
  "Acht",
  "Achtmaal",
  "Almkerk",
  "Alphen",
  "Altena",
  "Andel",
  "Asten",
  "Baarle-Nassau",
  "Baarschot",
  "Babyloniënbroek",
  "Bakel",
  "Bavel",
  "Beek en Donk",
  "Beers",
  "Bergeijk",
  "Bergen op Zoom",
  "Berghem",
  "Berkel-Enschot",
  "Berlicum",
  "Best",
  "Beugen",
  "Biest-Houtakker",
  "Biezenmortel",
  "Bladel",
  "Boekel",
  "Boerdonk",
  "Bokhoven",
  "Borkel en Schaft",
  "Boskant",
  "Bosschenhoofd",
  "Boxmeer",
  "Boxtel",
  "Breda",
  "Breugel",
  "Budel",
  "Budel-Dorplein",
  "Budel-Schoot",
  "Calfven",
  "Castelr",
  "Casteren",
  "Chaam",
  "Cromvoirt",
  "Cuijk",
  "Dalem",
  "De Heen",
  "De Moer",
  "De Mortel",
  "De Rips",
  "Demen",
  "Den Bosch",
  "Den Dungen",
  "Den Hout",
  "Deurne",
  "Deursen-Dennenburg",
  "Dieden",
  "Diessen",
  "Dinteloord",
  "Doeveren",
  "Dommelen",
  "Dongen",
  "Dongense Vaart",
  "Dorst",
  "Drimmelen",
  "Drongelen",
  "Drunen",
  "Duizel",
  "Dussen",
  "Eerde",
  "Eersel",
  "Eethen",
  "Effen",
  "Eindhoven",
  "Elsendorp",
  "Elshout",
  "Empel",
  "Engelen",
  "Erp",
  "Esbeek",
  "Esch",
  "Escharen",
  "Etten-Leur",
  "Fijnaart",
  "Galder",
  "Gassel",
  "Gastel",
  "Geertruidenberg",
  "Geffen",
  "Geldrop",
  "Gemert",
  "Gemonde",
  "Genderen",
  "Gerwen",
  "Gewande",
  "Giessen",
  "Gilze",
  "Goirle",
  "Grave",
  "Groeningen",
  "Haaren",
  "Haarsteeg",
  "Haghorst",
  "Halder",
  "Halsteren",
  "Handel",
  "Hank",
  "Hapert",
  "Haps",
  "Haren",
  "Hedikhuizen",
  "Heensche Molen",
  "Heerle",
  "Heesbeen",
  "Heesch",
  "Heeswijk-Dinther",
  "Heeze",
  "Heijningen",
  "Heimolen",
  "Helenaveen",
  "Helkant",
  "Helmond",
  "Helmond-'t Hout",
  "Helvoirt",
  "Helwijk",
  "Herpen",
  "Herpt",
  "Het Wild",
  "Heukelom",
  "Heusden",
  "Heusden-Vesting",
  "Hilvarenbeek",
  "Hoeven",
  "Holthees",
  "Hooge Mierde",
  "Hooge Zwaluwe",
  "Hoogeloon",
  "Hoogerheide",
  "Huijbergen",
  "Huisseling",
  "Huize Padua",
  "Hulsel",
  "Hulten",
  "Kaatsheuvel",
  "Katwijk",
  "Keent",
  "Keldonk",
  "Kladde",
  "Klein-Dongen",
  "Klein-Zundert",
  "Klundert",
  "Knegsel",
  "Koolwijk",
  "Kruisland",
  "Kruisstraat",
  "Lage Mierde",
  "Lage Zwaluwe",
  "Landhorst",
  "Langenboom",
  "Langeweg",
  "Ledeacker",
  "Leende",
  "Leenderstrijp",
  "Lennisheuvel",
  "Lepelstraat",
  "Liempde",
  "Lierop",
  "Lieshout",
  "Liessel",
  "Linden",
  "Lith",
  "Lithoijen",
  "Loon op Zand",
  "Loosbroek",
  "Luyksgestel",
  "Maarheeze",
  "Maashees",
  "Maaskantje",
  "Macharen",
  "Made",
  "Maliskamp",
  "Maren-Kessel",
  "Mariaheide",
  "Mariahout",
  "Meeuwen",
  "Megen",
  "Middelbeers",
  "Middelrode",
  "Mierlo",
  "Milheeze",
  "Mill",
  "Moerdijk",
  "Moergestel",
  "Moerstraten",
  "Molenschot",
  "Nederwetten",
  "Neerkant",
  "Netersel",
  "Nieuw Velp",
  "Nieuwe Vaart",
  "Nieuwendijk",
  "Nieuwkuijk",
  "Nieuw-Vossemeer",
  "Nijnsel",
  "Nispen",
  "Nistelrode",
  "Noordhoek",
  "Noordschans",
  "Nuenen",
  "Nuland",
  "Odiliapeel",
  "Oeffelt",
  "Oijen",
  "Oirschot",
  "Oisterwijk",
  "Olland",
  "Ommel",
  "Oosteind",
  "Oostelbeers",
  "Oosterhout",
  "Oploo",
  "Oss",
  "Ossendrecht",
  "Oud Gastel",
  "Oud Velp",
  "Oudemolen",
  "Oudenbosch",
  "Oudendijk",
  "Oudheusden",
  "Oventje",
  "Overlangel",
  "Overloon",
  "Prinsenbeek",
  "Putte",
  "Raamsdonk",
  "Raamsdonksveer",
  "Ravenstein",
  "Reek",
  "Reusel",
  "Riel",
  "Riethoven",
  "Rijen",
  "Rijkevoort",
  "Rijsbergen",
  "Rijswijk",
  "Roosendaal",
  "Rosmalen",
  "Rucphen",
  "'s Gravenmoer",
  "Sambeek",
  "Schaijk",
  "Schijf",
  "Schijndel",
  "Sint Agatha",
  "Sint Anthonis",
  "Sint Hubert",
  "Sint-Michielsgestel",
  "Sint-Oedenrode",
  "Sleeuwijk",
  "Soerendonk",
  "Someren",
  "Someren-Eind",
  "Someren-Heide",
  "Son",
  "Spoordonk",
  "Sprang-Capelle",
  "Sprundel",
  "St. Willebrord",
  "Stampersgat",
  "Standdaarbuiten",
  "Steenbergen",
  "Steensel",
  "Sterksel",
  "Stevensbeek",
  "Stiphout",
  "Strijbeek",
  "Teeffelen",
  "Terheijden",
  "Teteringen",
  "Tilburg",
  "Tonnekreek",
  "Uden",
  "Udenhout",
  "Uitwijk",
  "Ulicoten",
  "Ulvenhout",
  "Uppel",
  "Vaart",
  "Valkenswaard",
  "Veen",
  "Veghel",
  "Veldhoven",
  "Velp",
  "Venhorst",
  "Vessem",
  "Vianen",
  "Vierlingsbeek",
  "Vinkel",
  "Vliegbasis Gilze-Rijen",
  "Vliegbasis Volkel",
  "Vlierden",
  "Vlijmen",
  "Volkel",
  "Vorstenbosch",
  "Vortum-Mullem",
  "Vrijhoeve",
  "Vught",
  "Waalre",
  "Waalwijk",
  "Waardhuizen",
  "Wagenberg",
  "Walik",
  "Wanroij",
  "Waspik",
  "Weebosch",
  "Welberg",
  "Werkendam",
  "Wernhout",
  "Westelbeers",
  "Westerbeek",
  "Westerhoven",
  "Wijbosch",
  "Wijk en Aalburg",
  "Wilbertoord",
  "Willemstad",
  "Wintelre",
  "Woensdrecht",
  "Woudrichem",
  "Wouw",
  "Wouwse Plantage",
  "Zandoerle",
  "Zeeland",
  "Zegge",
  "Zeilberg",
  "Zevenbergen",
  "Zevenbergschen Hoek",
  "Zijtaart",
  "Zundert",
  "Zwingelspaan",
];

export const radiusOptions = [5, 10, 15, 25, 50];
